name: hydrosync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#BECDBF" # you can use a color or image for the background
  adaptive_icon_foreground: "assets/icon/icon.png" # for  adaptive icons on Android
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/crops/
    - assets/images/sensors/
